version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "haydnba"
      - "samcorneybeacon"
    groups:
      security-updates-minor-and-patch:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      versions-updates-minor-and-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
