name: 'Send slack notification'
description: 'Send a Slack notification of a successful build'
inputs:
  status:
    description: Specify success or failure or cancelled or custom.
    required: true
  slack_webhook_url:
    description: Webhook URL to send the Slack message to
    required: true
outputs:
  time: # output will be available to future steps 
    description: 'The message to output'
runs:
  using: 'node20'
  main: 'dist/index.js'
